
import type { IconName } from "@/components/ui/event-icon";

export const technicalEvents = [
  { 
    name: 'Codex', 
    slug: 'codex', 
    icon: 'codex' as IconName, 
    description: "Crack quantum ciphers and extract critical data.", 
    status: "Unlocked", 
    priority: "Critical", 
    mode: "Offline", 
    price: "₹25",
    rounds: "Round 1 - This round consists of multiple-choice questions focused on logical reasoning and basic mathematics.\nRound 2 - In this round, participants will tackle logic-based questions and must explain their reasoning to the Codex team. Participants who effectively explain their reasoning will move on to the subsequent rounds of the competition. The ultimate goal is to be the first to complete the final round, thereby achieving victory in the event.",
    rules: "1. Both the rounds are in OFFLINE mode.\n2. Participants will get a maximum of 1 hour to solve the questions in the first round.\n3. Every round is an elimination round.\n4. Use of unfair means will result in disqualification.\n5. The decision of the organizers will be considered final and binding on all the participants.",
    combos: "No combos available for the event",
    teamDistribution: "Only individual participation is allowed.",
    timeline: "Round 1:- 3rd & 4th October 2024 (Offline)\nRound 2:- 5th October 2024 11:00 am Onwards (Offline).",
    contacts: [{ name: "Siddhesh", phone: "8856862577" }, { name: "Tejas", phone: "7058389422" }],
  },
  { 
    name: 'Codelicious', 
    slug: 'codelicious', 
    icon: 'codelicious' as IconName, 
    description: "Disrupt defensive algorithms in rapid-fire code challenges.", 
    status: "Unlocked", 
    priority: "High", 
    mode: "Online", 
    price: "Free",
    rounds: "Round 1: This event comprises a single round and it will be conducted on CodeChef.",
    rules: "1. Participants must have a CodeChef account to compete.\n2. The contest duration is a maximum of 2 hours.\n3. Any unfair means will lead to immediate disqualification.\n4. The decision of the organizers will be considered final and binding on all the participants.",
    combos: "No combos available for the event",
    teamDistribution: "Only individual participation is allowed",
    timeline: "1st October 2024 8:00 pm - 10:00 pm (Online)",
    contacts: [{name: "Shreekar", phone: "7666439458"}, {name: "Prathamesh", phone: "8624021404"}],
  },
  { 
    name: 'Compute and Compete', 
    slug: 'compute-and-compete', 
    icon: 'compute' as IconName, 
    description: "Outmaneuver the AI in direct algorithmic combat.", 
    status: "Unlocked", 
    priority: "Medium", 
    mode: "Online + Offline", 
    price: "₹35",
    rounds: "Round 1 -Reverse Coding: Participants will be given 6-7 questions to solve and it will be conducted on Hackerrank.Questions will be in the form of input and output, challenging participants to deduce the underlying logic that connects them.\nRound 2- Bug-Off: Participants will be given code snippets to debug.Participants are provided with code snippets containing errors (such as logical and syntactical issues) and must correct the code to pass all test cases.",
    rules: "1. Participants need to have an account on HackerRank.\n 2. Participants will get a maximum of 1.5 hours to solve the questions in the first round.\n3. Any unfair means will lead to immediate disqualification\n4. Every round is an elimination round\n5. The decision of the organizers will be considered final and binding on all the participants.",
    combos: "No combos available for the event",
    teamDistribution: "Team of 2 (max). \nIndividual participation is also allowed. ",
    timeline: "Round 1:- 2nd October 5:00 pm - 6:30 pm (Online)\nRound 2:- 4th October 12:00 pm - 2:00 pm (Offline).",
    contacts: [{ name: "Aniket", phone: "8889904950" }, { name: "Shreenath", phone: "9146379805" }],
  },
  { 
    name: 'Dataquest', 
    slug: 'dataquest', 
    icon: 'dataquest' as IconName, 
    description: "Gather intelligence on the AI's data mining operations.", 
    status: "Locked", 
    priority: "Low", 
    mode: "Online", 
    price: "₹35",
    rounds: "FE-SE Category:\nRound 1 (Single Round)\nThere will be only one round.\nThe winners will be decided based on the chosen optimization metrics  (examples of metrics: RMSE, MAE, or R² for regression problems; Accuracy, Precision, F1-Score, or AUC-ROC for classification problems)\nMaximum of 3 submissions are allowed per day. The best score from the submissions will be considered for evaluation.\nTE-BE Category:\nRound 1\nThe first round will filter participants based on the chosen optimization metrics (examples of metrics: RMSE, MAE, or R² for regression problems; Accuracy, Precision, F1-Score, or AUC-ROC for classification problems)\nMaximum of 3 submissions are allowed per day. The best score from the submissions will be considered for evaluation.\nRound 2-\nQualified participants from Round 1 will move on to Round 2.\nSimilar to Round 1, a maximum of 3 submissions are allowed per day, and the best score will be considered for final evaluation.",
    rules: "1. The problem statement along with the dataset will be released on the platform\n.2. The link for the contest will be shared with the participants through email.\n3. Participants are expected to submit their CSV files along with .ipynb/py files.\n4.You can view the public leaderboard to compete against the best of the best solutions and achieve better results.\n5. The right to decide the optimization metric will rest with the judges and it will be final and binding (example: RMSE, MAE, or R² for regression problems; Accuracy, Precision, F1-Score, or AUC-ROC for classification problems)\n6. Any unfair means will lead to immediate disqualification.\n 7.Every round is an elimination round",
    combos: "No combos available for the event",
    teamDistribution: "Only individual participation is allowed.",
    timeline: "FE-SE Category\nRound 1:- Submission Timeline: 29th September 12:00 am - 1st October 12:00 pm (Online)\nTE-BE Category\nRound 1:- Submission Timeline: 29th September 12:00 am - 1st october 12:00 pm (Online)\nRound 2:- Submission Timeline: 2nd October 12:00 pm - 4th October 11:59 am (Online)",
    contacts: [{ name: "Soham", phone: "7620106310" }, { name: "Tanisha", phone: "9834050189" }],
  },
  { 
    name: 'Web n App', 
    slug: 'web-n-app', 
    icon: 'webapp' as IconName, 
    description: "Penetrate the AI's web and mobile command centers.", 
    status: "Unlocked", 
    priority: "High", 
    mode: "Online + Offline", 
    price: "₹90",
    rounds: "Round 1: PPT Submission The team can pick any one problem statement of their choice and work on the same. Participants will have to submit a ppt for the same. The judgment for this round will be on the basis of the following factors: - The originality and uniqueness of the idea. - Appropriateness and effectiveness of the chosen technologies and frameworks. - Clarity and functionality of the solution.\nRound 2 : Hackathon The selected teams from Round 1 will be asked to show the working web or app .\n The judgment of this round will be based on the following factors:\n 1.Maximum end-to-end implementation of the live/on-spot changes of features as directed by the judges of the event. \n2.Time execution, cleaner code and seamless working model/prototype of the application is desired.\n3.Frontend application(UI/UX) implementation.Extra points will be given to ML/Blockchain/AR-VR implementation and business potential \n4.This is final round and will be of 7-8 hours and will held offline at PICT",
    rules: " 1. Each Team can submit an entry for only one Problem Statement.\n2. Participants are expected to submit a PPT of the proposed solution and idea on the submission platform for round-1. Adding the link of the figma prototype or github repository in the PPT is optional but preferred.\n3. Use of web frameworks and any suitable tech stack is allowed but the use of ready-made templates is prohibited.\n4. The decision of the organizers and judges will be final and binding on all participants.\n5.For PPT use the template provided",
    combos: "No combos available for the event",
    teamDistribution: "1. FE-SE (junior category) : Groups of a maximum of 3 participants.\n2. TE-BE (senior category): Groups of a maximum of 4 participants.\n3. Only the team leader has to register for this event.",
    timeline: "Round 1:- Submission Timeline:- 27th September 12:00 am - 1st October 6:00 pm (On Pulzion Submission platform)\nRound 2: 4th October 9:00 am Onwards.\nProblem Statements are live",
    contacts: [{ name: "Soham", phone: "8446092629" }, { name: "Sachi", phone: "9049406726" }],
  },
  { 
    name: 'Electroquest', 
    slug: 'electroquest', 
    icon: 'electroquest' as IconName, 
    description: "Sabotage hardware infrastructure and disable quantum processors.", 
    status: "Locked", 
    priority: "Critical", 
    mode: "Offline", 
    price: "₹60",
    rounds: "Round 1:\n The first round is a treasure hunt across the campus using technical and electronics-related clues. The qualifying teams will recieve problem statements that very in difficulty based on the participants' academic year.\n Round 2:\n FE and SE/TE/BE students will tackle engaging circuit debugging and circuit design challenges.",
    rules: "Rules for Round 1:\n1.All the teams would be given a maximum of 2 hours to finish the treasure hunt.\n2. Use of the internet or any other resource is allowed during the treasure hunt.\n3. Any help or clarity on the proceedings of the event would be given by volunteers present on site.\n4. Hints related to the question will be provided by volunteers to the team by deducting the certain number of points per hint. (2 hints max).\nRules for Round 2:\n 1. For this round all teams have 1 hour for designing the circuit.\n2. Team can use the first 20 minutes for internet searching",
    combos: "No combos available for the event",
    teamDistribution: "Teams of 3 (max)\n1. FE\n2. SE/TE/BE\nNote- Only the team leader has to register for this event",
    timeline: "Round 1:- 1st October 4:00 pm  Onwards (Offline).\nRound 2:- 5th October 2:00 pm Onwards (Offline).",
    contacts: [{ name: "Aniket", phone: "8889904950" }, { name: "Srirang", phone: "9028832111" }],
  },
  { 
    name: 'Hire Hustle', 
    slug: 'hire-hustle', 
    icon: 'hirehustle' as IconName, 
    description: "Recruit new operatives while maintaining cover.", 
    status: "Unlocked", 
    priority: "Medium", 
    mode: "Online", 
    price: "₹50",
    rounds: "For FE-SE category:\nRound 1- Online Assessment (MCQs + 2 Coding questions)\nRound 2- Technical + HR interview (Techno-HR interview)\nFor TE-BE category:\nRound 1- Online Assessment (Coding round)\nRound 2- Technical interview\nRound 3- Technical + HR interview (Techno-HR interview)",
    rules: "1. For FE-SE category, first round will consist of technical and programming related MCQs and then coding questions.\n2. For TE-BE category, first round will consist of only coding questions.\n 3. Every round is an elimination round.\n 3. Candidates who advance to subsequent rounds will receive detailed interview schedules via email.\n 5. Any unfair means will lead to immediate disqualification.\n 6. The decisions made by the organizers and judges are final and binding.\n 7. All the rounds will be conducted in ONLINE mode",
    combos: "No combos available for the event",
    teamDistribution: "Only individual participation is allowed.",
    timeline: "Round 1 (Both categories) : 2nd October 10 am to 12 pm (Online)\nRound 2 (Both categories): 4th October (Online)\nRound 3 (Only TE - BE) : 5th October 9 onwards (Online)",
    contacts: [{ name: "Omkar", phone: "6300656863" }, { name: "Pranav", phone: "8766543106" }],
  },
  { 
    name: 'Dextrous', 
    slug: 'dextrous', 
    icon: 'dextrous' as IconName, 
    description: "Execute precise manual operations on core systems.", 
    status: "Locked", 
    priority: "Low", 
    mode: "Offline", 
    price: "₹50",
    rounds: "Round 1- A general multiple-choice quiz designed to assess your aptitude.\nRound 2- Group Discussion Round.\n Round 3- HR Interview Round.",
    rules: "1. Participants will get a maximum of 1 hour to solve the questions in the first round.\n 2. All the rounds are elimination rounds.\n 3.Any unfair means will lead to immediate disqualification.\n 4. The decision of the judges will be considered final and binding on all the participants.",
    combos: "No combos available for the event",
    teamDistribution: "Only individual participation is allowed.",
    timeline: "Round 1: Dates: 3rd October & 4th October (Offline)\nRound 2: 4th October 5:00 pm Onwards (Offline)\n Round 3: 5th October 10:00 am (Offline).",
    contacts: [{ name: "Anushree", phone: "8484024100" }, { name: "Madhura", phone: "9834396355" }],
  },
  { 
    name: 'Paper Presentation', 
    slug: 'paper-presentation', 
    icon: 'paper' as IconName, 
    description: "Present research findings on the AI's weaknesses.", 
    status: "Unlocked", 
    priority: "Medium", 
    mode: "Online", 
    price: "₹25",
    rounds: "Tracks: (Online mode)\n1) Idea presentation track - This track is for those who wish to pitch a research idea or demonstrate their understanding of a topic.\n2) Paper Presentation track -This track is for those who have done concrete research and wish to present their research findings before the judges.\nRound 1: Participants have to submit their paper/ Idea on the Submission Platform.\nRound 2:Shortlisted participants have to present their paper/idea to the judges.",
    rules: "1. Papers/Ideas must fall under one of the following domains – Blockchain, AI & ML\n 2.Ensure that your submission is a fully developed research paper, not merely an idea or abstract for the paper presentation and for Idea presentation, it must be a document which includes the idea, abstract, details, approach, and advantages. Anything else is a bonus.\n 3. The paper must be the original work of the participant, any plagiarized content will result in immediate disqualification.\n 4. All the rounds are elimination rounds.\n 5. Participants must submit their papers or ideas in PDF format.\n 6. The decision of the judges will be final and binding.",
    combos: "No combos available for the event",
    teamDistribution: "Only individual participation is allowed.",
    timeline: "Round 1: Submission Timeline: 27th September 12:00 am to 30th September 12:00 pm (Online)\n Round 2: 2nd October 12:00 am to 4th October 11:59 pm (Online)",
    contacts: [{ name: "Anjali", phone: "7058443037" }, { name: "Aditya", phone: "9426034129" }],
  },
  { 
    name: 'Innowave', 
    slug: 'innowave', 
    icon: 'innowave' as IconName, 
    description: "Develop innovative tech to counter adaptive AI.", 
    status: "Unlocked", 
    priority: "High", 
    mode: "Online + Offline", 
    price: "₹40",
    rounds: "Round 1- Case Submission Teams will select a case problem from one of four key themes and submit a 6-slider presentation outlining a solution.\nRound 2: Video Pitch Submission Selected teams will submit a 2-minute video pitch, presenting their solution in a compelling and concise format.\nRound 3: Final Case Presentation The top teams will present their solutions to judges and sponsors.",
    rules: "1. All team members must be from the same organization or institute, but they can be from different academic years. Interdisciplinary teams can participate.\n 2. Modification of team post registration will not be allowed.\n 3. All the team members must be present during the final presentation; otherwise, their entry will be disqualified.\n 4. Any unfair means will lead to immediate disqualification.\n 5. The decision of the judges will be considered final and binding on all the participants.",
    combos: "No combos available for the event",
    teamDistribution: "Teams of 2-4. The one who registers the team becomes the team leader.",
    timeline: "Round 1: Submission Timeline: 27th September 12:00 am to 29th September 11:59 pm (Online)\nRound 2: Submission Timeline: 1st October 3:00 pm to 3rd october 6:00 pm (Online)\n Round 3: 5th October 9:00 am Onwards (Hybrid Mode)",
    contacts: [{ name: "Harsha", phone: "9322678365" }, { name: "Anjali", phone: "8484802405" }],
  },
];

export const nonTechnicalEvents = [
    { 
      name: 'Fandom tmkoc', 
      slug: 'fandom-tmkoc', 
      icon: 'fandom' as IconName, 
      description: "Test your knowledge of the iconic TV show.", 
      status: "Unlocked", 
      priority: "Low", 
      mode: "Offline", 
      price: "₹40",
      rounds: "Round 1- This is an offline round featuring multiple-choice questions related to various fandom topics.\n Round 2- This round will showcase a unique format for each fandom, featuring a range of exciting offline games.\n Round 3- This round will be a surprise and will take place offline.",
      rules: "1. All the rounds are elimination rounds.\n 2.Use of any unfair means will result in direct disqualification.\n 3.The decision of the organizers will be final and binding on all participants.",
      combos: "No combos available for the event",
      teamDistribution: "Only individual participation is allowed.",
      timeline: "Round 1: 3rd October & 4th October (Offline)\n Round 2: 4th October 2:00 pm - 4:00 pm (Offline)\n Round 3: 5th October 12:00 pm Onwards (Offline)",
      contacts: [{ name: "Devashish", phone: "9607601090" }, { name: "Aakanksha", phone: "8530053300" }],
    },
    { 
      name: 'Fandom cricket', 
      slug: 'fandom-cricket', 
      icon: 'fandom' as IconName, 
      description: "Show off your expertise in the world of cricket.", 
      status: "Unlocked", 
      priority: "Low", 
      mode: "Offline", 
      price: "₹40",
      rounds: "Round 1- This is an offline round featuring multiple-choice questions related to various fandom topics.\n Round 2- This round will showcase a unique format for each fandom, featuring a range of exciting offline games.\n Round 3- This round will be a surprise and will take place offline.",
      rules: "1. All the rounds are elimination rounds.\n 2.Use of any unfair means will result in direct disqualification.\n 3.The decision of the organizers will be final and binding on all participants.",
      combos: "No combos available for the event",
      teamDistribution: "Only individual participation is allowed.",
      timeline: "Round 1: 3rd October & 4th October (Offline)\n Round 2: 4th October 2:00 pm - 4:00 pm (Offline)\n Round 3: 5th October 12:00 pm Onwards (Offline)",
      contacts: [{ name: "Devashish", phone: "9607601090" }, { name: "Aakanksha", phone: "8530053300" }],
    },
    { 
      name: 'Fandom football', 
      slug: 'fandom-football', 
      icon: 'fandom' as IconName, 
      description: "Prove you're a true fan of the beautiful game.", 
      status: "Unlocked", 
      priority: "Low", 
      mode: "Offline", 
      price: "₹40",
      rounds: "Round 1- This is an offline round featuring multiple-choice questions related to various fandom topics.\n Round 2- This round will showcase a unique format for each fandom, featuring a range of exciting offline games.\n Round 3- This round will be a surprise and will take place offline.",
      rules: "1. All the rounds are elimination rounds.\n 2.Use of any unfair means will result in direct disqualification.\n 3.The decision of the organizers will be final and binding on all participants.",
      combos: "No combos available for the event",
      teamDistribution: "Only individual participation is allowed.",
      timeline: "Round 1: 3rd October & 4th October (Offline)\n Round 2: 4th October 2:00 pm - 4:00 pm (Offline)\n Round 3: 5th October 12:00 pm Onwards (Offline)",
      contacts: [{ name: "Devashish", phone: "9607601090" }, { name: "Aakanksha", phone: "8530053300" }],
    },
    { 
      name: 'Fandom sitcom', 
      slug: 'fandom-sitcom', 
      icon: 'fandom' as IconName, 
      description: "Challenge your knowledge of popular sitcoms.", 
      status: "Unlocked", 
      priority: "Low", 
      mode: "Offline", 
      price: "₹40",
      rounds: "Round 1- This is an offline round featuring multiple-choice questions related to various fandom topics.\n Round 2- This round will showcase a unique format for each fandom, featuring a range of exciting offline games.\n Round 3- This round will be a surprise and will take place offline.",
      rules: "1. All the rounds are elimination rounds.\n 2.Use of any unfair means will result in direct disqualification.\n 3.The decision of the organizers will be final and binding on all participants.",
      combos: "No combos available for the event",
      teamDistribution: "Only individual participation is allowed.",
      timeline: "Round 1: 3rd October & 4th October (Offline)\n Round 2: 4th October 2:00 pm - 4:00 pm (Offline)\n Round 3: 5th October 12:00 pm Onwards (Offline)",
      contacts: [{ name: "Devashish", phone: "9607601090" }, { name: "Aakanksha", phone: "8530053300" }],
    },
    { 
      name: 'Fandom anime', 
      slug: 'fandom-anime', 
      icon: 'fandom' as IconName, 
      description: "A battle of wits for all anime enthusiasts.", 
      status: "Unlocked", 
      priority: "Low", 
      mode: "Offline", 
      price: "₹40",
      rounds: "Round 1- This is an offline round featuring multiple-choice questions related to various fandom topics.\n Round 2- This round will showcase a unique format for each fandom, featuring a range of exciting offline games.\n Round 3- This round will be a surprise and will take place offline.",
      rules: "1. All the rounds are elimination rounds.\n 2.Use of any unfair means will result in direct disqualification.\n 3.The decision of the organizers will be final and binding on all participants.",
      combos: "No combos available for the event",
      teamDistribution: "Only individual participation is allowed.",
      timeline: "Round 1: 3rd October & 4th October (Offline)\n Round 2: 4th October 2:00 pm - 4:00 pm (Offline)\n Round 3: 5th October 12:00 pm Onwards (Offline)",
      contacts: [{ name: "Devashish", phone: "9607601090" }, { name: "Aakanksha", phone: "8530053300" }],
    },
    { 
      name: 'Insight', 
      slug: 'insight', 
      icon: 'insight' as IconName, 
      description: "Gather intelligence through social interaction and wit.", 
      status: "Unlocked", 
      priority: "Medium", 
      mode: "Online + Offline", 
      price: "₹25",
      rounds: `Round 1- Participants write a letter to someone from the past or future (example. Someone you know, celebrity, any fictional characters, people that influence history), demonstrating their imagination and writing skills. It has to be submitted online within the given time slot. \nRound 2- The 2nd round will feature "What if..." scenarios, challenging participants to creatively explore hypothetical situations.`,
      rules: "1. Plagiarized entries will be disqualified.\n 2. Word limit for both the rounds is 400 words and participants should strictly maintain it.\n 3. Every round is an elimination round.\n 4. Any unfair means will lead to immediate disqualification.\n 5.The decision of the organizers will be considered final and binding on all the participants",
      combos: "No combos available for the event",
      teamDistribution: "Only individual participation is allowed.",
      timeline: "Round 1: Submission Timeline: 30th September 12:00 am to 2nd October 12:00 pm (Online)\nRound 2: 4th October 9:00 am Onwards (Offline)",
      contacts: [{ name: "Maitri", phone: "7975037272" }, { name: "Sonali", phone: "7875257646" }],
    },
    { 
      name: 'Freeze the second', 
      slug: 'freeze-the-second', 
      icon: 'freeze' as IconName, 
      description: "Capture time-sensitive intelligence in real-time.", 
      status: "Locked", 
      priority: "High", 
      mode: "Online", 
      price: "₹25",
      rounds: "The submission process consists of a single round in which you are required to submit your photograph",
      rules: "1. Each participant must submit only one photograph.\n2. Photographs must be taken by the submitting individual images should not be sourced from the internet or captured by others.\n 3.Participants must upload their photographs to the submission platform within the designated timeslot.\n4. Any use of unfair means will result in immediate disqualification.\n5. The organizers decisions are final and binding for all participants.",
      combos: "No combos available for the event",
      teamDistribution: "Only individual participation is allowed.",
      timeline: "Submission Timeline: 27th September 12:00 am - 4th October 12:00 pm (Online).",
      contacts: [{ name: "Gaurav", phone: "8484987616" }, { name: "Soumitra", phone: "9142002323" }],
    },
];

    